version: "3.3"
services:
    app-backend:
        # build: /
        image: app_backend
        container_name: backend
        restart: always
        ports:
            - 8082:8082
    app-frontend:
        # build: /
        image: macroplan
        container_name: frontend
        restart: always
        ports:
            - 4200:4200
        expose:
            - "4200"